### ISSUE TITLE
Extra spaces deleted on import

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ezfe/tellraw#251] opened 2019-04-29 19:56 UTC
Exported command:
{"command":"/tellraw @p %s","jobject":[{"text":"some          text"}],"jtemplate":"tellraw"}
Import, and immediately re-export:
{"command":"/tellraw @p %s","jobject":[{"text":"some text"}],"jtemplate":"tellraw"}

Upon importing, extra spaces are removed.

Edit: It seems github removes extra spaces also...
Here's an image:
![Capture](https://user-images.githubusercontent.com/22590237/56923029-8bd35680-6a97-11e9-94cc-366b9857f8bd.PNG)

**Comment by ezfe** [comment] 2019-04-29 20:11
I can't reproduce this, I copied yours and added spaces in a text editor

<img width="1033" alt="Screen Shot 2019-04-29 at 4 10 40 PM" src="https://user-images.githubusercontent.com/1449259/56923771-62b3c580-6a99-11e9-8795-9f8cd247e9c3.png">

I then copied that into the import box and it worked

<img width="799" alt="Screen Shot 2019-04-29 at 4 10 33 PM" src="https://user-images.githubusercontent.com/1449259/56923780-69423d00-6a99-11e9-838f-4e666caad255.png">

Are you doing something differently? I can also export and reimport after doing this.

**Comment by ThizThizzyDizzy** [comment] 2019-05-01 12:54
I think issue is with chrome, as the spaces disappear when I paste it in the box, before clicking OK
(If I manually re-add them, it does work)
Could a separate import box be added?

**Comment by ezfe** [comment] 2019-05-01 13:54
Should be fixed now

**Closed** 2019-05-01 13:54 UTC
