### ISSUE TITLE
Issue Report - Translation Issue (ru-RU)

### ISSUE THREAD

**Issue by AndrewRAN** [ezfe/tellraw#194] opened 2016-11-19 11:08 UTC
Please enter steps to reproduce the issue below, as well as any other information you want to include
(**RUSSIAN**) I found this:
![screenshot_1](https://cloud.githubusercontent.com/assets/23475741/20455008/656d31e8-ae72-11e6-8ba2-69b95ab115d2.png)
I don't know how to explain it. Just add translation strings.

 Provided Data - Do not modify below this line

```
[]
```

**Comment by ezfe** [comment] 2016-11-20 17:35
Duplicate of #192

**Closed by ezfe** 2016-11-20 17:35 UTC
